package com.example.voipapp.sdk.media

import io.github.jaredmdobson.concentus.OpusApplication
import io.github.jaredmdobson.concentus.OpusDecoder
import io.github.jaredmdobson.concentus.OpusEncoder
import io.github.jaredmdobson.concentus.OpusSignal


/**
 * SAudio Codec implementation using Opus. this Generated By AI
 * No idea what Ai Did :) all what i know Opus used for encode and decode :)
 */
object AudioCodec {

    private const val SAMPLE_RATE = 16000
    private const val CHANNELS = 1
    private const val FRAME_SIZE_SAMPLES = 320 // 20ms at 16kHz
    private const val MAX_PACKET_SIZE = 1275

    private val encoder = OpusEncoder(SAMPLE_RATE, CHANNELS, OpusApplication.OPUS_APPLICATION_VOIP).apply {
        bitrate = 32000
        signalType = OpusSignal.OPUS_SIGNAL_VOICE
        complexity = 5
    }

    private val decoder = OpusDecoder(SAMPLE_RATE, CHANNELS)

    fun encode(pcmData: ByteArray): ByteArray {
        val pcmShorts = ShortArray(pcmData.size / 2)
        for (i in pcmShorts.indices) {
            pcmShorts[i] = ((pcmData[i * 2 + 1].toInt() shl 8) or (pcmData[i * 2].toInt() and 0xff)).toShort()
        }

        val outData = ByteArray(MAX_PACKET_SIZE)
        val bytesEncoded = encoder.encode(pcmShorts, 0, FRAME_SIZE_SAMPLES, outData, 0, outData.size)
        
        return outData.copyOfRange(0, bytesEncoded)
    }

    fun decode(opusData: ByteArray): ByteArray {
        val outPcmShorts = ShortArray(FRAME_SIZE_SAMPLES)
        val samplesDecoded = decoder.decode(opusData, 0, opusData.size, outPcmShorts, 0, FRAME_SIZE_SAMPLES, false)
        
        val pcmData = ByteArray(samplesDecoded * 2)
        for (i in 0 until samplesDecoded) {
            val sample = outPcmShorts[i]
            pcmData[i * 2] = (sample.toInt() and 0xff).toByte()
            pcmData[i * 2 + 1] = ((sample.toInt() shr 8) and 0xff).toByte()
        }
        return pcmData
    }
}
